name: Run

on:
  workflow_dispatch:
  schedule:
  - cron: '23 5,11,23 * * *'
  - cron: '47 2,8,14 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  check_up:

    runs-on: ubuntu-latest

    env:
      CHECKUP_USERNAME: ${{ secrets.CHECKUP_USERNAME }}
      CHECKUP_PASSWORD: ${{ secrets.CHECKUP_PASSWORD }}
      CHECKUP_CAMPUS: ${{ secrets.CHECKUP_CAMPUS }}

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build
    - name: check up
      run: cargo run

