name: Auto Checkup

on:
  workflow_dispatch:
  schedule:
  # TODO: fix morning time issue
  - cron: '23 4,11,22 * * *'
  - cron: '47 8,14,23 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  checkup:

    runs-on: ubuntu-latest

    env:
      CHECKUP_USERNAME: ${{ secrets.CHECKUP_USERNAME }}
      CHECKUP_PASSWORD: ${{ secrets.CHECKUP_PASSWORD }}
      CHECKUP_CAMPUS: ${{ secrets.CHECKUP_CAMPUS }}

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: cargo build
    - name: checkup
      run: cargo run

